/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omarfhaar;

import java.io.File;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author mert
 */
public class initFrame extends javax.swing.JFrame {

    /**
     * Creates new form initFrame
     */
    
    public String path;
    
    public initFrame() {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_positiveDirChooser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_NegativeDirChooser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Omarfhaar");

        btn_positiveDirChooser.setText("CHOOSE PATH OF POSITIVE IMAGES");
        btn_positiveDirChooser.setName("btn_positiveDirChooser"); // NOI18N
        btn_positiveDirChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_positiveDirChooserActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        jLabel1.setText("Omarfhaar Haar Cascade Training Tool");

        btn_NegativeDirChooser.setText("CHOOSE PATH OF NEGATIVE IMAGES");
        btn_NegativeDirChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NegativeDirChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_positiveDirChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                            .addComponent(btn_NegativeDirChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(btn_positiveDirChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_NegativeDirChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_positiveDirChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_positiveDirChooserActionPerformed
        JFileChooser chooser = new JFileChooser();
        ManageDir mdp = new ManageDir();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.showOpenDialog(null);
        if(chooser.getSelectedFile() != null)
        {
        path = chooser.getSelectedFile().getAbsolutePath();
        mdp.setpath(path);
        File[] fList = mdp.listFiles();
        System.out.println("You chose : " + path);
            
                new MainFrame(fList);
            
        
        }
        
    }//GEN-LAST:event_btn_positiveDirChooserActionPerformed

    private void btn_NegativeDirChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NegativeDirChooserActionPerformed
        ManageDir mdn = new ManageDir();
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.showOpenDialog(null);
        
        if(fc.getSelectedFile() != null)
        {
            path = fc.getSelectedFile().getAbsolutePath();
            mdn.setpath(path);
            File[] fList = mdn.listFiles();
             
        try {
             File outputFile = new File(path + "/" + "negative.txt");
            
             FileWriter fw = new FileWriter(outputFile,true); 
             
             for (int i = 0; i < fList.length; i++) {
                
                 fw.write(fList[i].toString() + "\n");
             
             }
             fw.close();
             JOptionPane.showMessageDialog(null, "Text file for negative images succesfully created!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error occured while creating text file !" + "\n\n" + e.getMessage());
            
        }
        }
    }//GEN-LAST:event_btn_NegativeDirChooserActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_NegativeDirChooser;
    private javax.swing.JButton btn_positiveDirChooser;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
